site_name: fastapi-shield
site_description: Shield is a FastAPI decorator that provides a simple shield for your API Endpoints to shield off unwanted requests.
site_author: Jim Chng
repo_url: https://github.com/jymchng/fastapi-shield
repo_name: jymchng/fastapi-shield

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
      # Basic Usage Done
      - Basic Usage: user-guide/basic-usage.md
      # Authentication Patterns Done
      - Authentication Patterns: user-guide/authentication-patterns.md
      - Role-Based Access Control: user-guide/rbac.md
      - Type Wrapping: user-guide/type-wrapping.md
      - Custom Initialization: user-guide/custom-initialization.md
      - String Types: user-guide/string-types.md
      - Request Validation: user-guide/request-validation.md
      - API Examples: user-guide/examples.md
      - Troubleshooting: user-guide/troubleshooting.md
      - Comparison with Alternatives: user-guide/comparison_alternatives.md
  - Examples:
      - Basic Examples: examples/basic_examples.md
      # Basic Examples Done
      - Authentication Examples: examples/authentication_examples.md
      - Authorization Examples: examples/authorization_examples.md
      - Advanced Examples: examples/advanced_examples.md
      - Real World Examples: examples/real_world.md
      - Using with Pydantic: examples/using_with_pydantic.md
  - Advanced Topics:
      - Type Inheritance: advanced-topics/type-inheritance.md
      - JWT Authentication: advanced-topics/jwt-authentication.md
      - Dependency Injection: advanced-topics/dependency-injection.md
      - Method Interception: advanced-topics/method-interception.md
      - Security Best Practices: advanced-topics/security-best-practices.md
  - API Reference:
      - Overview: api/index.md
      - Shield: api/shield.md
      - NewType: api/newtype.md
      - Depends: api/depends.md
      - Validators: api/validators.md
      - Interceptors: api/interceptors.md
  - Development:
      - Overview: development/index.md
      - Contributing: development/contributing.md
      - Building: development/building.md
      - Testing: development/testing.md
      - Architecture: development/architecture.md
      - Roadmap: development/roadmap.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - tags
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: true
            find_stubs_package: true
            allow_inspection: false # to remove __file__ etc from c extension stubs
            extra:
              paths:
                - '**/*.pyi'
                - '!**/*.so'  # Exclude .so files
                - '!**/*.pyd'  # Exclude .pyd files