site_name: fastapi-shield
site_description: Shield is a FastAPI decorator that provides a simple shield for your API Endpoints to shield off unwanted requests.
site_author: Jim Chng
repo_url: https://github.com/jymchng/fastapi-shield
repo_name: jymchng/fastapi-shield

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
      - Basic Usage: user-guide/basic-usage.md
      - Authentication Patterns: user-guide/authentication-patterns.md
      - Role-Based Access Control: user-guide/rbac.md
      - Type Wrapping: user-guide/type-wrapping.md
      - Method Interception: user-guide/method-interception.md
      - Custom Initialization: user-guide/custom-initialization.md
      - String Types: user-guide/string-types.md
      - Request Validation: user-guide/request-validation.md
      - API Examples: user-guide/examples.md
  - Examples:
      - Basic Examples: examples/basic_examples.md
      - Authentication Examples: examples/authentication_examples.md
      - Authorization Examples: examples/authorization_examples.md
      - Advanced Examples: examples/advanced_examples.md
      - Real World Examples: examples/real_world.md
      - Using with Pydantic: examples/using_with_pydantic.md
      - Complete Application: examples/complete_application.md
  - Advanced Topics:
      - Type Inheritance: advanced-topics/type-inheritance.md
      - Advanced Method Interception: advanced-topics/method-interception.md
      - Rate Limiting: advanced-topics/rate-limiting.md
      - JWT Authentication: advanced-topics/jwt-authentication.md
      - IP Restrictions: advanced-topics/ip-restrictions.md
      - Shield Composition: advanced-topics/shield-composition.md
      - Performance Optimization: advanced-topics/performance-optimization.md
  - API Reference:
    - NewType: api/newtype.md
  - Development:
    - Contributing: development/contributing.md
    - Building: development/building.md
    - Testing: development/testing.md
    - Performance: development/performance.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
  - tags
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: true
            find_stubs_package: true
            allow_inspection: false # to remove __file__ etc from c extension stubs
          source:
            - '**/*.pyi'
            - '!**/*.so'  # Exclude .so files
            - '!**/*.pyd'  # Exclude .so files