"""FastAPI Shield - Protect your FastAPI endpoints with ease.

FastAPI Shield provides a powerful decorator-based system for intercepting and validating
requests before they reach your FastAPI endpoints. It enables you to create reusable
'shields' that can validate authentication, authorization, rate limiting, input sanitization,
and more.

Key Components:
    - Shield: The main decorator class for creating request interceptors
    - ShieldedDepends: Dependency injection wrapper for shield-aware dependencies
    - shield: Factory function for creating Shield instances

Usage:
    ```python
    from fastapi_shield import Shield, ShieldedDepends, shield

    # Create a shield using the decorator
    @shield
    def auth_shield(request: Request):
        # Your validation logic here
        return validated_data_or_none

    # Apply shield to endpoint
    @app.get("/protected")
    @auth_shield
    def protected_endpoint():
        return {"message": "Access granted"}
    ```

For more information, visit: https://github.com/jymchng/fastapi-shield
"""

from fastapi_shield.shield import Shield, ShieldedDepends, shield
from fastapi_shield.rate_limit import (
    RateLimitShield,
    RateLimitAlgorithm,
    RateLimitBackend,
    MemoryRateLimitBackend,
    rate_limit,
    per_ip_rate_limit,
    per_user_rate_limit,
)
from fastapi_shield.input_validation import (
    InputValidationShield,
    ValidationRule,
    SanitizationType,
    ValidationType,
    InputSanitizer,
    InputValidator,
    input_validation_shield,
    create_xss_protection_shield,
    create_sql_injection_protection_shield,
    create_email_validation_shield,
    create_length_validation_shield,
)
from fastapi_shield.cors_security import (
    CORSSecurityShield,
    CORSConfig,
    CORSPolicy,
    cors_shield,
    strict_cors_shield,
    public_cors_shield,
    dynamic_cors_shield,
    authenticated_cors_shield,
)

from fastapi_shield.cache_control import (
    CacheControlShield,
    CacheConfig,
    CachePolicy,
    CacheDirective,
    cache_control_shield,
    no_cache_shield,
    private_cache_shield,
    public_cache_shield,
    static_cache_shield,
    dynamic_cache_shield,
    conditional_cache_shield,
)
from fastapi_shield.audit_logging import (
    AuditLoggingShield,
    AuditLogConfig,
    LogEntry,
    LogLevel,
    LogFormat,
    SensitiveDataMask,
    AuditLogger,
    PythonAuditLogger,
    StructlogAuditLogger,
    FileAuditLogger,
    audit_logging_shield,
    sensitive_audit_shield,
    compliance_audit_shield,
    error_audit_shield,
    performance_audit_shield,
    debug_audit_shield,
)
from fastapi_shield.api_key_rotation import (
    APIKeyRotationShield,
    APIKeyRotationConfig,
    APIKey,
    KeyStatus,
    KeyRotationStrategy,
    NotificationLevel,
    KeyRotationEvent,
    KeyStore,
    MemoryKeyStore,
    NotificationHandler,
    LoggingNotificationHandler,
    WebhookNotificationHandler,
    api_key_rotation_shield,
    scoped_api_key_shield,
    admin_api_key_shield,
    read_only_api_key_shield,
)
from fastapi_shield.webhook_verification import (
    WebhookVerificationShield,
    WebhookConfig,
    WebhookVerificationResult,
    SignatureAlgorithm,
    WebhookProvider,
    ReplayProtection,
    MemoryReplayProtection,
    SignatureValidator,
    HMACSignatureValidator,
    GitHubSignatureValidator,
    StripeSignatureValidator,
    PayPalSignatureValidator,
    SlackSignatureValidator,
    github_webhook_shield,
    stripe_webhook_shield,
    paypal_webhook_shield,
    slack_webhook_shield,
    custom_webhook_shield,
)
from fastapi_shield.circuit_breaker import (
    CircuitBreakerShield,
    CircuitBreakerConfig,
    CircuitMetrics,
    CircuitState,
    HealthChecker,
    HTTPHealthChecker,
    CallbackHealthChecker,
    CircuitBreakerMonitor,
    LoggingMonitor,
    MetricsCollectorMonitor,
    get_circuit_breaker,
    register_circuit_breaker,
    get_all_circuit_breakers,
    circuit_breaker_shield,
    database_circuit_breaker_shield,
    external_service_circuit_breaker_shield,
    high_availability_circuit_breaker_shield,
)
from fastapi_shield.content_type_validation import (
    ContentTypeShield,
    ContentTypeConfig,
    ContentTypeValidationResult,
    ContentTypeValidator,
    ContentTypePolicy,
    SecurityLevel,
    MIME_TYPE_GROUPS,
    content_type_shield,
    json_content_type_shield,
    file_upload_content_type_shield,
    form_content_type_shield,
    api_content_type_shield,
)
from fastapi_shield.request_size_limit import (
    RequestSizeLimitShield,
    RequestSizeLimitConfig,
    RequestSizeTracker,
    SizeViolation,
    SizeUnit,
    SizeContentTypeCategory,
    SizeCheckMode,
    convert_size_to_bytes,
    format_bytes,
    request_size_limit_shield,
    json_size_limit_shield,
    file_upload_size_limit_shield,
    api_size_limit_shield,
    strict_size_limit_shield,
)
from fastapi_shield.bot_detection import (
    BotDetectionShield,
    BotDetectionConfig,
    BotDetectionResult,
    BotDetector,
    UserAgentAnalyzer,
    BehavioralAnalyzer,
    BehavioralMetrics,
    RequestFingerprint,
    BotType,
    DetectionMethod,
    BotAction,
    ChallengeType,
    bot_detection_shield,
    strict_bot_detection_shield,
    search_engine_friendly_shield,
)
from fastapi_shield.session_management import (
    SessionShield,
    SessionConfig,
    SessionData,
    SessionManager,
    SessionStorage,
    MemorySessionStorage,
    SessionState,
    SessionSecurityLevel,
    SessionStorageType,
    CSRFProtection,
    session_management_shield,
    secure_session_shield,
    api_session_shield,
)
from fastapi_shield.sql_injection_detection import (
    SQLInjectionShield,
    SQLInjectionConfig,
    SQLInjectionDetector,
    SQLPatternLibrary,
    InjectionDetection,
    DetectionLevel,
    SQLDialect,
    InjectionType,
    ActionPolicy,
    sql_injection_detection_shield,
    strict_sql_injection_shield,
    monitoring_sql_injection_shield,
)
# LDAP Authentication imports removed - module not implemented yet
from fastapi_shield.multi_factor_auth import (
    MFAShield,
    MFAConfig,
    MFASession,
    MFAChallenge,
    MFAUser,
    MFAManager,
    TOTPGenerator,
    TOTPConfig,
    SMSConfig,
    EmailConfig,
    BackupCodeConfig,
    MFAMethod,
    MFAProvider,
    MFAStatus,
    CodeGenerator,
    multi_factor_auth_shield,
    enterprise_mfa_shield,
    flexible_mfa_shield,
)
from fastapi_shield.api_versioning import (
    APIVersioningShield,
    APIVersioningConfig,
    VersioningStrategy,
    VersionFormat,
    DeprecationLevel,
    VersionValidationResult,
    VersionInfo,
    VersionExtractor,
    HeaderVersionExtractor,
    QueryParamVersionExtractor,
    PathVersionExtractor,
    AcceptHeaderVersionExtractor,
    URIVersionExtractor,
    VersionValidator,
    UsageTracker,
    APIVersionManager,
    api_versioning_shield,
    semantic_versioning_shield,
    url_path_versioning_shield,
    accept_header_versioning_shield,
)
from fastapi_shield.request_tracing import (
    RequestTracingShield,
    RequestTracingConfig,
    TracingBackend,
    SpanKind,
    TracingLevel,
    SpanAttribute,
    SpanEvent,
    TraceContext,
    TracingMetrics,
    TracerProvider,
    OpenTelemetryProvider,
    JaegerProvider,
    ZipkinProvider,
    DatadogProvider,
    RequestTracer,
    request_tracing_shield,
    detailed_tracing_shield,
    performance_tracing_shield,
    error_tracing_shield,
    jaeger_tracing_shield,
    zipkin_tracing_shield,
    datadog_tracing_shield,
)
from fastapi_shield.graphql_query_depth import (
    GraphQLQueryDepthShield,
    GraphQLQueryDepthConfig,
    GraphQLQueryParser,
    RegexGraphQLParser,
    ASTGraphQLParser,
    GraphQLQueryType,
    ComplexityCalculationStrategy,
    QueryAnalysisResult,
    FieldComplexity,
    graphql_query_depth_shield,
    create_strict_graphql_shield,
    create_permissive_graphql_shield,
    create_production_graphql_shield,
)
# Database connection imports commented out - module not implemented yet
# from fastapi_shield.database_connection import (
#     DatabaseConnectionShield,
#     DatabaseConnectionConfig,
#     ConnectionPool,
#     DatabaseConnection,
#     GenericDatabaseConnection,
#     ConnectionMetrics,
#     QueryResult,
#     DatabaseType,
#     ConnectionState,
#     PoolState,
#     RetryStrategy,
#     RetryManager,
#     database_connection_shield,
#     postgresql_connection_shield,
#     mysql_connection_shield,
#     redis_connection_shield,
#     high_availability_database_shield,
# )
from fastapi_shield.feature_flag import (
    FeatureFlagShield,
    FeatureFlagConfig,
    FeatureFlagProvider,
    FeatureFlagCache,
    EvaluationResult,
    RolloutStrategy,
    LaunchDarklyProvider,
    SplitProvider,
    UnleashProvider,
    CustomProvider,
    feature_flag_shield,
    launchdarkly_feature_flag_shield,
    split_feature_flag_shield,
    unleash_feature_flag_shield,
    percentage_rollout_shield,
    authenticated_feature_flag_shield,
)
from fastapi_shield.performance_monitoring import (
    PerformanceMonitoringShield,
    PerformanceMonitoringConfig,
    MonitoringServiceProvider,
    PrometheusProvider,
    DataDogProvider,
    NewRelicProvider,
    CustomProvider,
    MetricsStorage,
    ResourceMonitor,
    AlertManager,
    AlertThreshold,
    Alert,
    PerformanceMetric,
    ResourceUsage,
    MonitoringService,
    AlertSeverity,
    MetricType,
    performance_monitoring_shield,
    prometheus_performance_shield,
    datadog_performance_shield,
    newrelic_performance_shield,
    multi_provider_performance_shield,
)

__version__ = "0.1.1"

__all__ = [
    "Shield", 
    "ShieldedDepends", 
    "shield",
    "RateLimitShield",
    "RateLimitAlgorithm",
    "RateLimitBackend",
    "MemoryRateLimitBackend",
    "rate_limit",
    "per_ip_rate_limit",
    "per_user_rate_limit",
    "InputValidationShield",
    "ValidationRule",
    "SanitizationType",
    "ValidationType",
    "InputSanitizer",
    "InputValidator",
    "input_validation_shield",
    "create_xss_protection_shield",
    "create_sql_injection_protection_shield",
    "create_email_validation_shield",
    "create_length_validation_shield",
    "CORSSecurityShield",
    "CORSConfig",
    "CORSPolicy",
    "cors_shield",
    "strict_cors_shield",
    "public_cors_shield",
    "dynamic_cors_shield",
    "authenticated_cors_shield",

    "CacheControlShield",
    "CacheConfig",
    "CachePolicy",
    "CacheDirective",
    "cache_control_shield",
    "no_cache_shield",
    "private_cache_shield",
    "public_cache_shield",
    "static_cache_shield",
    "dynamic_cache_shield",
    "conditional_cache_shield",
    "AuditLoggingShield",
    "AuditLogConfig",
    "LogEntry",
    "LogLevel",
    "LogFormat",
    "SensitiveDataMask",
    "AuditLogger",
    "PythonAuditLogger",
    "StructlogAuditLogger",
    "FileAuditLogger",
    "audit_logging_shield",
    "sensitive_audit_shield",
    "compliance_audit_shield",
    "error_audit_shield",
    "performance_audit_shield",
    "debug_audit_shield",
    "APIKeyRotationShield",
    "APIKeyRotationConfig",
    "APIKey",
    "KeyStatus",
    "KeyRotationStrategy",
    "NotificationLevel",
    "KeyRotationEvent",
    "KeyStore",
    "MemoryKeyStore",
    "NotificationHandler",
    "LoggingNotificationHandler",
    "WebhookNotificationHandler",
    "api_key_rotation_shield",
    "scoped_api_key_shield",
    "admin_api_key_shield",
    "read_only_api_key_shield",
    "WebhookVerificationShield",
    "WebhookConfig",
    "WebhookVerificationResult",
    "SignatureAlgorithm",
    "WebhookProvider",
    "ReplayProtection",
    "MemoryReplayProtection",
    "SignatureValidator",
    "HMACSignatureValidator",
    "GitHubSignatureValidator",
    "StripeSignatureValidator",
    "PayPalSignatureValidator",
    "SlackSignatureValidator",
    "github_webhook_shield",
    "stripe_webhook_shield",
    "paypal_webhook_shield",
    "slack_webhook_shield",
    "custom_webhook_shield",
    "CircuitBreakerShield",
    "CircuitBreakerConfig",
    "CircuitMetrics",
    "CircuitState",
    "HealthChecker",
    "HTTPHealthChecker",
    "CallbackHealthChecker",
    "CircuitBreakerMonitor",
    "LoggingMonitor",
    "MetricsCollectorMonitor",
    "get_circuit_breaker",
    "register_circuit_breaker",
    "get_all_circuit_breakers",
    "circuit_breaker_shield",
    "database_circuit_breaker_shield",
    "external_service_circuit_breaker_shield",
    "high_availability_circuit_breaker_shield",
    "ContentTypeShield",
    "ContentTypeConfig",
    "ContentTypeValidationResult",
    "ContentTypeValidator",
    "ContentTypePolicy",
    "SecurityLevel",
    "MIME_TYPE_GROUPS",
    "content_type_shield",
    "json_content_type_shield",
    "file_upload_content_type_shield",
    "form_content_type_shield",
    "api_content_type_shield",
    "RequestSizeLimitShield",
    "RequestSizeLimitConfig",
    "RequestSizeTracker",
    "SizeViolation",
    "SizeUnit",
    "SizeContentTypeCategory",
    "SizeCheckMode",
    "convert_size_to_bytes",
    "format_bytes",
    "request_size_limit_shield",
    "json_size_limit_shield",
    "file_upload_size_limit_shield",
    "api_size_limit_shield",
    "strict_size_limit_shield",
    "BotDetectionShield",
    "BotDetectionConfig",
    "BotDetectionResult",
    "BotDetector",
    "UserAgentAnalyzer",
    "BehavioralAnalyzer",
    "BehavioralMetrics",
    "RequestFingerprint",
    "BotType",
    "DetectionMethod",
    "BotAction",
    "ChallengeType",
    "bot_detection_shield",
    "strict_bot_detection_shield",
    "search_engine_friendly_shield",
    "SessionShield",
    "SessionConfig",
    "SessionData",
    "SessionManager",
    "SessionStorage",
    "MemorySessionStorage",
    "SessionState",
    "SessionSecurityLevel",
    "SessionStorageType",
    "CSRFProtection",
    "session_management_shield",
    "secure_session_shield",
    "api_session_shield",
    "SQLInjectionShield",
    "SQLInjectionConfig",
    "SQLInjectionDetector",
    "SQLPatternLibrary",
    "InjectionDetection",
    "DetectionLevel",
    "SQLDialect",
    "InjectionType",
    "ActionPolicy",
    "sql_injection_detection_shield",
    "strict_sql_injection_shield",
    "monitoring_sql_injection_shield",
# LDAP Authentication exports removed - module not implemented yet
    "MFAShield",
    "MFAConfig",
    "MFASession",
    "MFAChallenge",
    "MFAUser",
    "MFAManager",
    "TOTPGenerator",
    "TOTPConfig",
    "SMSConfig",
    "EmailConfig",
    "BackupCodeConfig",
    "MFAMethod",
    "MFAProvider",
    "MFAStatus",
    "CodeGenerator",
    "multi_factor_auth_shield",
    "enterprise_mfa_shield",
    "flexible_mfa_shield",
    "APIVersioningShield",
    "APIVersioningConfig",
    "VersioningStrategy",
    "VersionFormat",
    "DeprecationLevel",
    "VersionValidationResult",
    "VersionInfo",
    "VersionExtractor",
    "HeaderVersionExtractor",
    "QueryParamVersionExtractor",
    "PathVersionExtractor",
    "AcceptHeaderVersionExtractor",
    "URIVersionExtractor",
    "VersionValidator",
    "UsageTracker",
    "APIVersionManager",
    "api_versioning_shield",
    "semantic_versioning_shield",
    "url_path_versioning_shield",
    "accept_header_versioning_shield",
    "RequestTracingShield",
    "RequestTracingConfig",
    "TracingBackend",
    "SpanKind",
    "TracingLevel",
    "SpanAttribute",
    "SpanEvent",
    "TraceContext",
    "TracingMetrics",
    "TracerProvider",
    "OpenTelemetryProvider",
    "JaegerProvider",
    "ZipkinProvider",
    "DatadogProvider",
    "RequestTracer",
    "request_tracing_shield",
    "detailed_tracing_shield",
    "performance_tracing_shield",
    "error_tracing_shield",
    "jaeger_tracing_shield",
    "zipkin_tracing_shield",
    "datadog_tracing_shield",
    "GraphQLQueryDepthShield",
    "GraphQLQueryDepthConfig",
    "GraphQLQueryParser",
    "RegexGraphQLParser",
    "ASTGraphQLParser",
    "GraphQLQueryType",
    "ComplexityCalculationStrategy",
    "QueryAnalysisResult",
    "FieldComplexity",
    "graphql_query_depth_shield",
    "create_strict_graphql_shield",
    "create_permissive_graphql_shield",
    "create_production_graphql_shield",
    # Database connection exports commented out - module not implemented yet
    # "DatabaseConnectionShield",
    # "DatabaseConnectionConfig",
    # "ConnectionPool",
    # "DatabaseConnection",
    # "GenericDatabaseConnection",
    # "ConnectionMetrics",
    # "QueryResult",
    # "DatabaseType",
    # "ConnectionState",
    # "PoolState",
    # "RetryStrategy",
    # "RetryManager",
    # "database_connection_shield",
    # "postgresql_connection_shield",
    # "mysql_connection_shield",
    # "redis_connection_shield",
    # "high_availability_database_shield",
    "FeatureFlagShield",
    "FeatureFlagConfig",
    "FeatureFlagProvider",
    "FeatureFlagCache",
    "EvaluationResult",
    "RolloutStrategy",
    "LaunchDarklyProvider",
    "SplitProvider",
    "UnleashProvider",
    "CustomProvider",
    "feature_flag_shield",
    "launchdarkly_feature_flag_shield",
    "split_feature_flag_shield",
    "unleash_feature_flag_shield",
    "percentage_rollout_shield",
    "authenticated_feature_flag_shield",
    "PerformanceMonitoringShield",
    "PerformanceMonitoringConfig",
    "MonitoringServiceProvider",
    "PrometheusProvider",
    "DataDogProvider",
    "NewRelicProvider",
    "CustomProvider",
    "MetricsStorage",
    "ResourceMonitor",
    "AlertManager",
    "AlertThreshold",
    "Alert",
    "PerformanceMetric",
    "ResourceUsage",
    "MonitoringService",
    "AlertSeverity",
    "MetricType",
    "performance_monitoring_shield",
    "prometheus_performance_shield",
    "datadog_performance_shield",
    "newrelic_performance_shield",
    "multi_provider_performance_shield",
]
